# Generated by Django 5.2.8 on 2025-11-30 23:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedOTPDevice',
            fields=[
                ('name', models.CharField(help_text='The human-readable name of this device.', max_length=64)),
                ('confirmed', models.BooleanField(default=True, help_text='Is this device ready for use?')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('otp_encrypted', models.CharField(blank=True, max_length=256, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('otp_expiry', models.DateTimeField(blank=True, null=True)),
                ('used', models.BooleanField(default=False)),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('max_failed_attempts', models.PositiveIntegerField(default=5)),
                ('last_request_time', models.DateTimeField(blank=True, null=True)),
                ('next_allowed_request_time', models.DateTimeField(blank=True, null=True)),
                ('cooldown_multiplier', models.FloatField(default=2.0)),
                ('lock_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique identifier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('device_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('browser', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('device', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(default=None, help_text='When this trusted device will expire')),
                ('is_active', models.BooleanField(default=True)),
                ('max_sessions', models.PositiveIntegerField(default=5, help_text='Maximum number of concurrent trusted devices allowed')),
            ],
            options={
                'verbose_name': 'Trusted Device',
                'verbose_name_plural': 'Trusted Devices',
                'db_table': 'trusted_devices',
                'ordering': ['-last_login'],
            },
        ),
    ]
