# Generated by Django 5.2.8 on 2025-11-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trusteddevice',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='The IP address of the trusted device.', null=True),
        ),
    ]
